# 방송 콘텐츠 대화체 음성인식 데이터
dir_name: 001.방송 콘텐츠 대화체 음성인식 데이터
compressed_format: zip
file_patterns:
  - 01.데이터/1.Training/라벨링데이터/*.zip
  - 01.데이터/2.Validation/라벨링데이터/*.zip
file_format: json
file_encoding: utf-8
sentence_extraction:
  - .utterance[]|.original_form
