# 대규모 구매도서 기반 한국어 말뭉치 데이터
dir_name: 029.대규모 구매도서 기반 한국어 말뭉치 데이터
compressed_format: zip
file_patterns:
  - 01.데이터/1.Training/라벨링데이터/*.zip
  - 01.데이터/2.Validation/라벨링데이터/*.zip
file_format: json
file_encoding: utf-8
data_structure: |-
  {
      "paragraphs": [
          {
              "sentences": [
                  {
                      "text": "string"
                  }
              ]
          }
      ]
  }
document_extraction: |-
  for paragraph in root.paragraphs:
      document_content = ""
      for sentence in paragraph.sentences:
          document_content += f"{sentence.text}\n"
      transformed_document = {"text": document_content.strip()}
      transformed_documents.append(transformed_document)
sentence_extraction:
  - .paragraphs[]|.sentences[]|.text
