# 도서자료 기계독서
dir_name: 도서자료 기계독해
compressed_format: zip
file_patterns:
  - '**/*.zip'
file_format: json
file_encoding: utf-8
sentence_extraction:
  - .data[]|.title
  - .data[]|.agency
  - .data[]|.paragraphs[]|.context
  - .data[]|.paragraphs[]|.qas[]|.question
  - .data[]|.paragraphs[]|.qas[]|.answers[]|.text
