file_names:
  - NIKL_DIALOGUE_2022_v1.0_JSON
compressed_format: zip
file_prefixes:
  - SDRW
file_format: json
file_encoding: utf-8
data_structure: |-
  {
      "document": [
          {
              "metadata": {
                  "speaker": [
                      {
                          "id": "string"
                      }
                  ]
              },
              "utterance": [
                  {
                      "form": "string",
                      "speaker_id": "string"
                  }
              ]
          }
      ]
  }
document_extraction: |-
  for document in root.document:
      speaker_ids = {speaker.id: idx for idx, speaker in enumerate(document.metadata.speaker, start=1)}
      document_content = ""
      for utterance in document.utterance:
          document_content += f'P{speaker_ids[utterance.speaker_id]}: {utterance.form}\n'
      transformed_document = {"text": document_content.strip()}
      transformed_documents.append(transformed_document)
sentence_extraction:
  - .document[]|.utterance[]|.form
special_tags:
  - "{laughing}"
  - "{clearing}"
  - "{singing}"
  - "{applausing}"
  - "((추정 전사))"
  - "((xx))"
  - "(())"
  - "~"
  - "-불완전 발화-"
deidentified_tags:
  - "&name&"
  - "&social-security-num&"
  - "&card-num&"
  - "&address&"
  - "&tel-num&"
  - "&company-name&"
